spring:
  application:
    name: cloud
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.cloud.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  servlet:
    session:
      timeout: 30m